import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const app = readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8");
const experience = readFileSync(new URL("../src/data/payExperienceUtils.js", import.meta.url), "utf8");
assert.match(app, /getEmployeePayExperience/);
assert.equal((app.match(/function PayTimelineTab\s*\(/g) || []).length, 1);
assert.doesNotMatch(app, /function PayTab\s*\(/);
const pay = app.slice(app.indexOf("function PayTimelineTab"), app.indexOf("function TimelineCard"));
const layout = app.slice(app.indexOf("function PayExperienceLayout"), app.indexOf("function TimelineCard"));
assert.match(pay, /Planning estimate/);
assert.match(experience, /Short-Term Disability/);
assert.match(pay, /How your pay is delivered/);
assert.match(experience, /separate Lincoln check/);
assert.match(experience, /may be paid separately by the state/);
assert.match(pay, /experience\.jobProtectionGuidance/);
assert.doesNotMatch(layout, /dailyBusinessDayRate|daily business-day rate|source salary target|Source fields|source report|source record|record classification|Administrative owner|ATP|benefit gross|payable calculated salary|Biweekly Base-Pay Target|Assumed State Benefit Offset|Lincoln Estimate After State Offset|Lincoln after state offset|State assumed maximum|planning component/i);
assert.doesNotMatch(layout, />[^<{]*\bSTD\b[^<{]*</i);
assert.match(pay, /experience\.stateAdjustment/);
assert.match(pay, /experience\.components/);
assert.match(pay, /ParentalCoordinationCard/);
assert.match(pay, /experience\.scenario === "parental"/);
assert.match(pay, /Paid parental leave/);
assert.match(pay, /ParentalCoordinationCard experience=\{experience\}/);
assert.doesNotMatch(pay, /money\(amount\)/);
assert.match(pay, /paid parental leave coordination/i);
assert.match(pay, /experience\.payPeriod/);
assert.match(pay, /StateProgramCapDetails/);
assert.match(pay, /stateProgram\.calculatedMaximum/);
assert.match(pay, /Calculated maximum for this pay period/);
console.log("Employee pay UI validation passed.");
