import assert from "node:assert/strict";
import { getStateCoordinationExperience } from "../src/data/stateCoordinationExperience.js";
import { getEmployeePriorityActions } from "../src/data/actionPlanUtils.js";
import { readFileSync } from "node:fs";

const options = { asOfDate: "2026-08-27", payPeriodFrom: "2026-08-01", payPeriodThrough: "2026-08-14" };
const employee = (state, category, extra = {}) => ({ state, leaveCategory: category, leaveBeginDate: "2026-08-01", leaveEndDate: "2026-08-31", payPeriodFromDate: "2026-08-01", payPeriodThruDate: "2026-08-14", biweeklySalaryAmount: "10275.24", sourceRecords: [{ state, leaveCategory: category, leaveBeginDate: "2026-08-01", leaveEndDate: "2026-08-31", payPeriodFromDate: "2026-08-01", payPeriodThruDate: "2026-08-14", biweeklySalaryAmount: "10275.24", product: "STD", ...extra }] });
const nyMedical = getStateCoordinationExperience(employee("NY", "OWN_MEDICAL"), options);
assert.equal(nyMedical.programName, "Disability Benefits Law (DBL)");
assert.equal(nyMedical.statusLabel, "Included in this planning estimate");
assert.equal(nyMedical.weeklyMaximum, 170);
assert.equal(nyMedical.calculatedMaximum, 340);
assert(nyMedical.concurrentLeaveExplanation && nyMedical.estimateExplanation && nyMedical.awardExplanation);
const nyBonding = getStateCoordinationExperience(employee("NY", "BONDING"), options);
assert.equal(nyBonding.programName, "NY Paid Family Leave (PFL)");
assert.equal(nyBonding.statusLabel, "Included in this planning estimate");
const caMedical = getStateCoordinationExperience(employee("CA", "OWN_MEDICAL"), options);
assert.equal(caMedical.programName, "State Disability Insurance (SDI)");
const txMedical = getStateCoordinationExperience(employee("TX", "OWN_MEDICAL"), options);
assert.equal(txMedical.statusLabel, "No state benefit estimate included");
assert.equal(txMedical.weeklyMaximum, null);
const unknown = getStateCoordinationExperience(employee("NY", "UNKNOWN"), options);
assert.equal(unknown.statusLabel, "No state benefit estimate included");
assert.equal(unknown.calculatedMaximum, null);
for (const key of ["sourceCategory", "category", "programType", "applicationOwner", "lincolnCoordination", "awardLetterRecipient", "ruleId"]) assert.equal(Object.hasOwn(nyMedical, key), false);
const customProgram = { stateCode: "CA", stateName: "California", programName: "Example Disability Benefit", programStatus: "Active", programType: "MEDICAL", benefitsStartDate: "2020-01-01", benefitsEndDate: null, maximumYear: 2026, maximumWeeklyBenefit: 500, familyLeaveWeeks: null, medicalLeaveWeeks: 26, coveredLeaveCategories: ["OWN_MEDICAL"], applicationOwner: "Employee", applicationUrl: "https://example.com/apply", officialProgramUrl: "https://example.com", eligibilityDescription: "Basic program information" };
const direct = getEmployeePriorityActions(employee("CA", "OWN_MEDICAL"), { ...options, programs: { CA: [customProgram] } });
assert.equal(direct.filter((item) => item.title === "Apply for your state benefit").length, 1);
const app = readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8");
assert.equal((app.match(/<StateStatutoryCard\s+employee=\{employee\}\s*\/>/g) || []).length, 1);
assert.match(app, /function PayTimelineTab[\s\S]*?<StateStatutoryCard\s+employee=\{employee\}\s*\/>/);
assert.doesNotMatch(app.slice(app.indexOf("function LifecycleOverview"), app.indexOf("function PayTimelineTab")), /<StateStatutoryCard/);
console.log("State coordination presentation and routing validation passed.");
